### PR TITLE
🕷 `urllib3` version bug

### PR DESCRIPTION
**Pull request by mrharpo**
# urllib3 bug
Avoids bug in urllib3 v2.0.2
```
AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'
```
Discoved in: https://github.com/WGBH-MLA/sonyci/actions/runs/4885453696/jobs/8719799443

Pins version to latest resolved version: `~=1.26`

Upstream bug report: https://github.com/urllib3/urllib3/issues/3017

### CODE REVIEW

**Comment by sethmlarson** [comment]
The fix for the issue you referenced is not to pin urllib3, instead use the `urllib3.connection` module, not `urllib3.connectionpool` module.

**Review by afred — APPROVED** [review]
👍

**Comment by sethmlarson** [comment]
@afred You've merged this PR, but I do not think it's the correct fix. Please see my comment here: https://github.com/WGBH-MLA/sonyci/pull/4#issuecomment-1535239300

In this configuration, your users won't be able to use the latest urllib3 features in other projects and other packages will be held back. The correct fix is to fix the import to use the correct module.

**Comment by sethmlarson** [comment]
@afred  understood, sorry for the confusion. Thanks for everything!

**Pull request merged**
